# Site settings
title: Firmy's blog
description: "Firmy's blog"
baseurl: "/" # for test: remove string '/space-jekyll-template' to ''
url: "http://firmianay.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Firmy Yang
user_title: security researcher
email: firmianay@gmail.com
twitter_username: firmianay1
github_username:  firmianay
gplus_username:  firmianay
linkedin_public_url: firmianay # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: firmianay
profile_picture: https://github.com/firmianay/firmianay.github.io/blob/master/avatar.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/firmianay
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/firmianay1
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: CTF-All-In-One
    url: https://github.com/firmianay/CTF-All-In-One
  - name: security-paper
    url: https://github.com/firmianay/security-paper

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
